sudo: required
services:
  - docker

before_install:
  - docker build -t kimi/docker-react -f Dockerfile.dev .

# script:
#   - docker run kimi/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true kimi/docker-react yarn test